version: 1

disable_existing_loggers: true

formatters:
  simple:
    format: "%(asctime)s [%(levelname)s]- %(message)s"

  default:
    format: "[%(name)s:%(lineno)d] %(asctime)s [%(levelname)s]- %(message)s"

  venbose:
    format: "[%(name)s][%(asctime)s][%(levelname)s] %(message)s (%(pathname)s:%(lineno)d)"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    maxBytes: 1000000 # 1Mb
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [file, console]

